### ISSUE TITLE
도커 컴포즈 구성

### ISSUE THREAD

**Issue by MALLLAG** [MoonKimTeam/backend-user#1]

**Comment by DonggeonMoon** [comment]
```yaml
version: '3'
services:
  # 유저 서비스
  user-service:
    image: openjdk:17
    volumes:
      - /Users/{사용자명}/docker-volume/user-service:/usr/src/app
    networks:
      - backend
    depends_on:
      - user-db
  # 유저 서비스 DB
  user-db:
    image: mysql:latest
    environment:
      TZ: "Asia/Seoul"
      MYSQL_DATABASE: "user"
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - /Users/{사용자명}/docker-volume/user-db:/var/lib/mysql
    networks:
      - backend
  # 공연 서비스
  concert-service:
    image: openjdk:17
    volumes:
      - /Users/{사용자명}/docker-volume/concert-service:/usr/src/app
    networks:
      - backend
    depends_on:
      - concert-db
  # 공연 서비스 DB
  concert-db:
    image: mysql:latest
    environment:
      TZ: "Asia/Seoul"
      MYSQL_DATABASE: "concert"
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - /Users/{사용자명}/docker-volume/concert-db:/var/lib/mysql
    networks:
      - backend
  # 결제 서비스
  payment-service:
    image: openjdk:17
    volumes:
      - /Users/{사용자명}/docker-volume/payment-service:/usr/src/app
    networks:
      - backend
    depends_on:
      - payment-db
  # 결제 서비스 DB
  payment-db:
    image: mysql:latest
    environment:
      TZ: "Asia/Seoul"
      MYSQL_DATABASE: "payment"
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - /Users/{사용자명}/docker-volume/payment-db:/var/lib/mysql
    networks:
      - backend
  # 알림 서비스
  notification-service:
    image: openjdk:17
    volumes:
      - /Users/{사용자명}/docker-volume/notification-service:/usr/src/app
    networks:
      - backend
    depends_on:
      - notification-db
  # 알림 서비스 DB
  notification-db:
    image: mysql:latest
    environment:
      TZ: "Asia/Seoul"
      MYSQL_DATABASE: "notifications"
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - /Users/{사용자명}/docker-volume/notification-db:/var/lib/mysql
    networks:
      - backend

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - backend

  redis:
    image: redis:latest
    networks:
      - backend

networks:
  backend:
    driver: bridge
```
